source: upstream_pr_merge_commits
patches:
  cloud-provider-aws:
    base_commit: 924fd6f22e6e80162b4df315dad0d01819bdf61c
    gold_commit: 73428cd2b02f8d1163a038297d8e740578acfd8e
    merge_commit: cd6188774fa4fde9be5f9e0735864095d97a2167
    patch_source: concatenated_upstream_pr_diffs
    upstream_prs:
    - 1214
  kops:
    base_commit: dad816791cd7d65d66f37f01d72e9a5dc26ecba6
    gold_commit: 04ce51ab56d6ca7b41a761eb8c09ad01ca011a61
    merge_commit: 7ae0bae6fc9b22597ca413d0f788a6752b7e1c0f
    patch_source: concatenated_upstream_pr_diffs
    upstream_prs:
    - 17521
hidden_tests:
  policy: upstream test-file diffs only
