source: upstream_pr_merge_commits
patches:
  awx:
    base_commit: 94d5769f32e72e973ae8d410d8fe1d240b960b3e
    gold_commit: 83c01cae12a42ddd3ca16d238a4776f37bcc033b
    merge_commit: 36a00ec46bd47226923298309b3387759f82f581
    patch_source: concatenated_upstream_pr_diffs
    upstream_prs:
    - 16209
  django-ansible-base:
    base_commit: 1b7ae7085675ca2c4a778e17dc5b61e619087fcb
    gold_commit: 1f032a8ab9dfa59a72cb7db2fdd1b9ebecf4bd2b
    merge_commit: 4296d118c62518ddca14382b546cc3af65efb127
    patch_source: concatenated_upstream_pr_diffs
    upstream_prs:
    - 922
hidden_tests:
  policy: upstream test-file diffs only
